/*
   Simple +/-/* expression language; 
   parser evaluates constant expressions on the fly
*/

package cup.example;

import java_cup.runtime.*;
import cup.example.Lexer;
import java.io.IOException;
import java.io.File;
import java.io.FileInputStream;


parser code {:
  protected Lexer lexer;
:}

/* define how to connect to the scanner! */
init with {:
  ComplexSymbolFactory f = new ComplexSymbolFactory();
  symbolFactory = f;
  File file = new File("input.txt");
  FileInputStream fis = null;
  try {
    fis = new FileInputStream(file);
  } catch (IOException e) {
    e.printStackTrace();
  } 
  lexer = new Lexer(f,fis);
:};
scan with {: return lexer.next_token(); :};

/* Terminals (tokens returned by the scanner). */
terminal SEMI, PLUS, MINUS, UMINUS, TIMES, DIVIDE;
terminal LPAR, RPAR, LBRACE, RBRACE, LBRACK, RBRACK;
terminal IF, ELSE, WHILE, RETURN, WRITE, READ, LENGTH;
terminal GREATER, LESS, ASSIGN, EQUALEQUAL, NEQUAL, NOT;  
terminal Integer NUMBER;        
terminal INT;
terminal CHAR;
terminal String NAME;
terminal Char QCHAR;

/* Non terminals */
non terminal            expr_list;
non terminal Integer    expr;      // used to store evaluated subexpressions

/* Precedences */
precedence left PLUS, MINUS;
precedence left TIMES, DIVIDE;
precedence left GREATER, LESS;
precedence left EQUALEQUAL, NEQUAL;
precedence left UMINUS;



/* The grammar rules */
expr_list ::= expr_list expr:e SEMI         {: System.out.println(e); :}
            | expr:e SEMI                   {: System.out.println(e); :}
            ;
            
expr      ::= expr:e1 PLUS  expr:e2         {: RESULT = e1+e2;        :}
             | expr:e1 MINUS expr:e2        {: RESULT = e1-e2;        :}
             | expr:e1 TIMES expr:e2        {: RESULT = e1*e2;        :}
              | expr:e1 DIVIDE expr:e2       {: RESULT = e1/e2;        :}
             | expr:e1 GREATER expr:e2        {: RESULT = (e1 > e2) ? 1 : 0;:}
			 | expr:e1 LESS expr:e2     {: RESULT = (e1 > e2) ? 1 : 0; :}
             | MINUS expr:e                 {: RESULT = -e;           :} 
              %prec UMINUS
             | LPAR expr:e RPAR	         {: RESULT = e;           :}
             | NUMBER:n	                     {: RESULT = n;           :}
             ;

       